const barbies = [
  {
    id: 1,
    nome: "Barbie Original",
    profissao: "Modelo de moda",
    anoLancamento: 1959,
  },
  {
    id: 2,
    nome: "Barbie Astronauta",
    profissao: "Astronauta",
    anoLancamento: 1965,
  },
  {
    id: 3,
    nome: "Barbie Cirurgiã",
    profissao: "Cirurgiã",
    anoLancamento: 1973,
  },
  {
    id: 4,
    nome: "Barbie Estrela do Rock",
    profissao: "Cantora",
    anoLancamento: 1986,
  },
  {
    id: 5,
    nome: "Barbie Presidente",
    profissao: "Presidente",
    anoLancamento: 1992,
  },
  {
    id: 6,
    nome: "Barbie Veterinária",
    profissao: "Veterinária",
    anoLancamento: 1996,
  },
  {
    id: 7,
    nome: "Barbie Princesa da Ilha",
    profissao: "Princesa",
    anoLancamento: 2007,
  },
  {
    id: 8,
    nome: "Barbie Heroína do Game",
    profissao: "Atleta de videogame",
    anoLancamento: 2017,
  },
  {
    id: 9,
    nome: "Barbie Chefe de Cozinha",
    profissao: "Chefe de cozinha",
    anoLancamento: 1998,
  },
  {
    id: 10,
    nome: "Barbie Bombeira",
    profissao: "Bombeira",
    anoLancamento: 1994,
  },
  {
    id: 11,
    nome: "Barbie Bailarina",
    profissao: "Bailarina",
    anoLancamento: 1999,
  },
  {
    id: 12,
    nome: "Barbie Nadadora Olímpica",
    profissao: "Atleta olímpica",
    anoLancamento: 2000,
  },
  {
    id: 13,
    nome: "Barbie Piloto de F-1",
    profissao: "Piloto",
    anoLancamento: 2005,
  },
  {
    id: 14,
    nome: "Barbie Geóloga",
    profissao: "Geóloga",
    anoLancamento: 2011,
  },
  {
    id: 15,
    nome: "Barbie Engenheira Robótica",
    profissao: "Engenheira",
    anoLancamento: 2018,
  },
  {
    id: 16,
    nome: "Barbie Cientista",
    profissao: "Cientista",
    anoLancamento: 2019,
  },
  {
    id: 17,
    nome: "Barbie Apicultora",
    profissao: "Apicultora",
    anoLancamento: 2019,
  },
  {
    id: 18,
    nome: "Barbie Artista Plástica",
    profissao: "Artista plástica",
    anoLancamento: 1989,
  },
  {
    id: 19,
    nome: "Barbie Surfista",
    profissao: "Surfista",
    anoLancamento: 2004,
  },
  {
    id: 20,
    nome: "Barbie Florista",
    profissao: "Florista",
    anoLancamento: 2001,
  },
  {
    id: 21,
    nome: "Barbie Paleontóloga",
    profissao: "Paleontóloga",
    anoLancamento: 2020,
  },
  {
    id: 22,
    nome: "Barbie Produtora Musical",
    profissao: "Produtora musical",
    anoLancamento: 2021,
  },
  {
    id: 23,
    nome: "Barbie Enfermeira",
    profissao: "Enfermeira",
    anoLancamento: 2003,
  },
  {
    id: 24,
    nome: "Barbie Atriz de Cinema",
    profissao: "Atriz",
    anoLancamento: 2002,
  },
  {
    id: 25,
    nome: "Barbie Jornalista",
    profissao: "Jornalista",
    anoLancamento: 1990,
  },
  {
    id: 26,
    nome: "Barbie Designer de Moda",
    profissao: "Designer de moda",
    anoLancamento: 1980,
  },
  {
    id: 27,
    nome: "Barbie Sereia",
    profissao: "Sereia",
    anoLancamento: 2010,
  },
  {
    id: 28,
    nome: "Barbie Professora",
    profissao: "Professora",
    anoLancamento: 2008,
  },
  {
    id: 29,
    nome: "Barbie Fazendeira",
    profissao: "Fazendeira",
    anoLancamento: 2016,
  },
  {
    id: 30,
    nome: "Barbie Pescadora",
    profissao: "Pescadora",
    anoLancamento: 2020,
  },
  {
    id: 31,
    nome: "Barbie Ciclista",
    profissao: "Ciclista",
    anoLancamento: 2018,
  },
  {
    id: 32,
    nome: "Barbie Treinadora de Cães",
    profissao: "Treinadora de cães",
    anoLancamento: 2006,
  },
  {
    id: 33,
    nome: "Barbie Desenvolvedora de Games",
    profissao: "Desenvolvedora de games",
    anoLancamento: 2016,
  },
  {
    id: 34,
    nome: "Barbie Tenista",
    profissao: "Tenista",
    anoLancamento: 1997,
  },
  {
    id: 35,
    nome: "Barbie Fotógrafa",
    profissao: "Fotógrafa",
    anoLancamento: 2009,
  },
  {
    id: 36,
    nome: "Barbie Arqueóloga",
    profissao: "Arqueóloga",
    anoLancamento: 2015,
  },
  {
    id: 37,
    nome: "Barbie Bióloga Marinha",
    profissao: "Bióloga marinha",
    anoLancamento: 2021,
  },
  {
    id: 38,
    nome: "Barbie Chef de Confeitaria",
    profissao: "Confeiteira",
    anoLancamento: 2013,
  },
  {
    id: 39,
    nome: "Barbie Exploradora",
    profissao: "Exploradora",
    anoLancamento: 2020,
  },
  {
    id: 40,
    nome: "Barbie Patinadora Artística",
    profissao: "Patinadora",
    anoLancamento: 2000,
  },
  {
    id: 41,
    nome: "Barbie Esquiadora",
    profissao: "Esquiadora",
    anoLancamento: 2022,
  },
  {
    id: 42,
    nome: "Barbie Estilista",
    profissao: "Estilista",
    anoLancamento: 2014,
  },
  {
    id: 43,
    nome: "Barbie Youtuber",
    profissao: "Youtuber",
    anoLancamento: 2017,
  },
  {
    id: 44,
    nome: "Barbie Cantora Popstar",
    profissao: "Cantora pop",
    anoLancamento: 2002,
  },
  {
    id: 45,
    nome: "Barbie Rainha da Neve",
    profissao: "Rainha",
    anoLancamento: 2012,
  },
  {
    id: 46,
    nome: "Barbie Treinadora de Golf",
    profissao: "Treinadora de golf",
    anoLancamento: 2007,
  },
  {
    id: 47,
    nome: "Barbie Mágica",
    profissao: "Mágica",
    anoLancamento: 2005,
  },
  {
    id: 48,
    nome: "Barbie Princesa das Fadas",
    profissao: "Fada",
    anoLancamento: 2010,
  },
  {
    id: 49,
    nome: "Barbie Espiã Secreta",
    profissao: "Espiã",
    anoLancamento: 2016,
  },
  {
    id: 50,
    nome: "Barbie Chefe de Polícia",
    profissao: "Chefe de polícia",
    anoLancamento: 2020,
  },
];

export default { barbies };
